server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://board-db-new.c3me2e6s4zzs.ap-northeast-2.rds.amazonaws.com:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:default_jwt_secret}
  expiration: 3600000  # 1 hour

# Swagger UI 기본 경로
springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG

cors:
  allowed-origins:
    - https://your-frontend-domain.com